config/routes.rb
Rails.application.routes.draw do
  resources :locations do
  	resources :recordings
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :recordings, dependent: :destroy
	validates :name, presence: true,
			length: { minimum: 3 }
end

app/models/recording.rb
class Recording < ApplicationRecord
	belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	http_basic_authenticate_with name: "username", password: "password", except: [:index, :show]

	def new
		@location = Location.new
	end

	def create
		@location = Location.new(location_params)

		if @location.save
			redirect_to @location
		else
			render 'new'
		end
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])

		if @location.update(location_params)
    		redirect_to @location
  		else
    		render 'edit'
  		end
	end

	def index
  		@locations = Location.all
	end

	def show
		@location = Location.find(params[:id])
	end

	def destroy
		@location = Location.find(params[:id])
		@location.destroy

		redirect_to locations_path
	end

	private
		def location_params
			params.require(:location).permit(:name)
		end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController

	http_basic_authenticate_with name: "username", password: "password", except: [:index, :show]

	def create
		@location = Location.find(params[:location_id])
		@recording = @location.recordings.create(recording_params)
		redirect_to location_path(@location)
	end

	def destroy
		@location = Location.find(params[:location_id])
		@recording = @location.recordings.find(params[:id])
		@recording.destroy
		redirect_to location_path(@location)
	end

	private
		def recording_params
			params.require(:recording).permit(:temp, :status)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clima</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  	<% if @location.errors.any? %>
	  	<div id="error_explanation">
	    	<h2><%= pluralize(@location.errors.count, "error") %> Este cambio
	    	no puede ser guardado:</h2>
	    	<ul>
	    		<% @location.errors.full_messages.each do |msg| %>
	      			<li><%= msg %></li>
	    		<% end %>
	    	</ul>
	  	</div>
  	<% end %>
  
  	<p>
    	<%= f.label :name %><br>
    	<%= f.text_field :name %>
  	</p>
 
  	<p>
    	<%= f.submit %>
  	</p>
<% end %>
<%= link_to 'Back', locations_path %>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<%= render 'form' %>

app/views/locations/index.html.erb
<h1>Listing Locations</h1>

<table>
  <tr>
    <th>Locations</th>
    <th colspan="3"></th>
  </tr>
 
  <% @locations.each do |location| %>
    <tr>
      	<td><%= location.name %></td>
      	<td><%= link_to 'Show', location_path(location) %></td>
      	<td><%= link_to 'Edit', edit_location_path(location) %></td>
      	<td><%= link_to 'Destroy', location_path(location),
                    method: :delete, data: { confirm: 'Desea eliminar?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'New Location', new_location_path %> 

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

app/views/locations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<h2>Recordings</h2>
<%= render @location.recordings %>

<h2>Add Recording</h2>
<%= render "recordings/form" %>

<%= link_to 'Edit Location', edit_location_path(@location) %> |
<%= link_to 'Back to Locations', locations_path %>

app/views/recordings/_form.html.erb
<%= form_for([@location, @location.recordings.build]) do |f| %>
  <p>
    <%= f.label :temp %><br>
    <%= f.text_field :temp %>
  </p>
  <p>
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/recordings/_recording.html.erb
<p>
  <strong>Temp:</strong>
  <%= recording.temp %>
</p>

<p>
  <strong>Status:</strong>
  <%= recording.status %>
</p>

<p>
  <%= link_to 'Destroy Recording', [recording.location, recording],
               method: :delete,
               data: { confirm: 'Desea eliminar?' } %>
</p>

app/views/welcome/index.html.erb
<h1>Weather, Rails</h1>

<%= link_to 'List Locations', controller: 'locations' %>